# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a60fb33482f5a7b0d2955d9263e39b4c59f1a8c7ed46dc86891400f7af6fcb1c5672b0cebfa8882667f7dbe2eee755ebdcf19b1cfcb28095844646db4499319b

test:
  secret_key_base: dced48db36557aefa02ef0e4ac7b3b3e9bd980e2f8679e3e135ddb28ea8b2268907711f7fffd939bdcc801e09edb6e46c42f3b02187f8838d9df32b040981421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
